version: "3"
services:
  react-app:
    container_name: react-app
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 80:3000
    volumes:
      - /app/node_modules
      - ./:/app

    
    